# Generated by Django 2.1.2 on 2019-02-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshoot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery2015_16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Upload/2015_16')),
                ('caption', models.CharField(max_length=1000)),
                ('image_date', models.DateField()),
                ('date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery2016_17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Upload/2016_17')),
                ('caption', models.CharField(max_length=1000)),
                ('image_date', models.DateField()),
                ('date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery2017_18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Upload/2017_18')),
                ('caption', models.CharField(max_length=1000)),
                ('image_date', models.DateField()),
                ('date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery2018_19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Upload/2018_19')),
                ('caption', models.CharField(max_length=1000)),
                ('image_date', models.DateField()),
                ('date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
